### ISSUE TITLE
suggestions from 'michelem'

### ISSUE THREAD

**Issue by Habbie** [dns-channel/dns-channel.github.io#7]
```
11:07Z --> michelem (~Adium@213.55.176.153) has joined #dns
11:17Z <michelem> hey folks. A couple of comments on the website:
11:17Z <michelem> 1. it'd be nice for users to read a note, in the "nameservers or proxies" table — on what's the primary attribute of each software. E.g add a column "Focus" with "Features" for BIND, "security" for djbdns etc.
11:17Z <michelem> 2. Tools — c-ares is missing. One of the more important libraries. https://c-ares.haxx.se . Also, consider adding our Delegation Lab tool, to visualize and troubleshoot delegation: https://www.buddyns.com/delegation-lab/cs.ucsb.edu https://www.buddyns.com/delegation-lab/ox.ac.uk
11:17Z <michelem> 3. Authoritative services — BuddyNS also has an API
13:07Z <-- michelem (~Adium@213.55.176.153) has quit (Quit: Leaving.)
```

**Comment by twkmhnnomn** [comment]
suggestion #2 and #3 handled as requested.

i'm not sure what to do about michelem's first suggestion.  if people deserve to know that, for example, djbdns is focused on security they also deserve to know that all output from djb about that s/w ceased almost a decade ago.  similarly the suggested focuses seem to imply that bind doesn't focus on security -- they do have multiple people involved so it isn't impossible.  overall this seems too contentious to me but if someone else wants to try to determine the 'focus' of each piece of s/w and update the table accordingly i'm not entirely against it.

**Comment by Habbie** [comment]
Let's close this.
